cyoa-step2:cyoa-step2.cpp story.hpp story.cpp page.hpp page.cpp
	g++ -o cyoa-step2 -ggdb3 -Wall -Werror -pedantic -std=gnu++98 cyoa-step2.cpp story.hpp story.cpp page.cpp page.hpp
cyoa-step1:cyoa-step1.cpp page.hpp page.cpp	
	g++ -o cyoa-step1 -ggdb3 -Wall -Werror -pedantic -std=gnu++98 cyoa-step1.cpp page.cpp page.hpp 
